services:
  backend:
    build: ./backend/
    container_name: priceops_django_api
    command: >
      sh -c "gunicorn core.wsgi:application -c /app/gunicorn.conf.py"
    env_file:
      - ./backend/.env
      - ./.env            
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
      - media_data:/app/media
    restart: always
  
  front:
    container_name: front
    restart: always
    build:
      context: ./frontend/.
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: priceops_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - media_data:/app/media/
    ports:
      - "80:80"
    depends_on:
      - backend
      - front
    restart: always

  db:
    image: postgres:15
    container_name: priceops_postgres_db
    restart: always
    env_file:
      - ./.env            
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: priceops_redis_cache
    restart: always
    env_file:
      - ./.env
    ports:
      - "6379:6379"

  celery:
    build:
      context: ./backend/
      dockerfile: Dockerfileml
    container_name: priceops_celery_worker
    # Limit concurrency and recycle worker children to reduce memory usage/OOM risk.
    # -c 1                          -> single concurrent worker process
    # --max-tasks-per-child=50     -> recycle child after 50 tasks (prevents mem growth)
    # --time-limit / --soft-time-limit -> hard/soft task timeouts (seconds)
    # --prefetch-multiplier=1      -> avoid prefetching many tasks into a worker
    command: >
      sh -c "celery -A core worker --loglevel=info -E -c 1 --max-tasks-per-child=1 --prefetch-multiplier=1"
    env_file:
      - ./backend/.env
      - ./.env
    depends_on:
      - backend
      - redis
      - db
    volumes:
      - ./backend:/app
      - media_data:/app/media
    restart: always

  celery_beat:
    build: ./backend/
    container_name: priceops_celery_beat
    command: >
      sh -c "celery -A core beat --loglevel=info"
    env_file:
      - ./backend/.env
      - ./.env            
    depends_on:
      - redis
      - db
    volumes:
      - ./backend:/app
    restart: always

  flower:
    container_name: priceops_flower
    build:
      context: ./backend/
    restart: always
    command: >
      celery -A core flower 
            --port=5555 
            --address=0.0.0.0 
            --broker=${REDIS_URL} 
            --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD}
    ports:
      - "5555:5555"
    env_file:
      - ./backend/.env
      - ./.env            
    environment:
      - FLOWER_USER=${FLOWER_USER}
      - FLOWER_PASSWORD=${FLOWER_PASSWORD}
    depends_on:
      - redis
      - celery

volumes:
  postgres_data:
  media_data:
