services:
  backend:
    build: ./backend/
    container_name: priceops_django_api
    command: >
      sh -c "python manage.py migrate &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
      - ./.env               # Root env for DB credentials
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    restart: always

  db:
    image: postgres:15
    container_name: priceops_postgres_db
    restart: always
    env_file:
      - ./.env               # Root env for DB credentials
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: priceops_redis_cache
    restart: always
    env_file:
      - ./.env               # Root env for Redis (if needed)
    ports:
      - "6379:6379"

  celery:
    build: ./backend/
    container_name: priceops_celery_worker
    command: >
      sh -c "celery -A core worker --loglevel=info -E"
    env_file:
      - ./backend/.env
      - ./.env               # Root env for DB credentials
    depends_on:
      - backend
      - redis
      - db
    volumes:
      - ./backend:/app
    restart: always

  celery_beat:
    build: ./backend/
    container_name: priceops_celery_beat
    command: >
      sh -c "celery -A core beat --loglevel=info"
    env_file:
      - ./backend/.env
      - ./.env               # Root env for DB credentials
    depends_on:
      - redis
      - db
    volumes:
      - ./backend:/app
    restart: always

  flower:
    container_name: priceops_flower
    build:
      context: ./backend/
    restart: always
    command: >
      celery -A core flower 
            --port=5555 
            --address=0.0.0.0 
            --broker=${REDIS_URL} 
            --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD}
    ports:
      - "5555:5555"
    env_file:
      - ./backend/.env
      - ./.env               # Root env for DB credentials
    environment:
      - FLOWER_USER=${FLOWER_USER}
      - FLOWER_PASSWORD=${FLOWER_PASSWORD}
    depends_on:
      - redis
      - celery

volumes:
  postgres_data:
